title: Cyber where? Where your Cyber will be - IT-Sec conferences. 
description: Cyber where? Where your Cyber will be - IT-Sec conferences.
author: Cyber where? Community

domain: "cyber-where.github.io"
baseurl: "https://cyber-where.github.io/"
repository: "cyber-where/cyber-where.github.io"

twitter_hashtag: 
github_username: cyber-where
github_repo: cyber-where.github.io

markdown: kramdown
ga_id:

include: ['_pages']
