title: Cyber where? IT-Sec Conferences 
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Cyber where? Community

domain: "cyber-where.github.io"
baseurl: "https://cyber-where.github.io/"
repository: "https://github.com/cyber-where/cyber-where.github.io"

twitter_hashtag: 
github_username: cyber-where
github_repo: cyber-where.github.io

markdown: kramdown
ga_id:

include: ['_pages']
